# Generated by Django 2.1.3 on 2018-11-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='overTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overDate', models.DateField(verbose_name='加班日期')),
                ('startTime', models.TimeField(verbose_name='开始时间')),
                ('endTime', models.TimeField(verbose_name='结束时间')),
                ('overTimeCause', models.CharField(max_length=255, verbose_name='加班事由')),
            ],
            options={
                'verbose_name': '加班统计',
                'verbose_name_plural': '加班统计',
                'db_table': 'overtime',
            },
        ),
        migrations.CreateModel(
            name='Vmms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=255, verbose_name='车型')),
                ('engineDisplacement', models.CharField(blank=True, max_length=10, verbose_name='发动机排量')),
                ('gearBox', models.CharField(blank=True, max_length=100, verbose_name='变速箱')),
                ('VIN', models.CharField(max_length=17, verbose_name='VIN码')),
                ('engineNumber', models.CharField(max_length=17, verbose_name='发动机号')),
                ('mileage', models.IntegerField(verbose_name='里程(KM)')),
                ('recipient', models.CharField(max_length=5, verbose_name='接车人')),
                ('sampleDate', models.DateField(verbose_name='接车时间')),
                ('returnDate', models.DateField(blank=True, verbose_name='还车时间')),
                ('useTest', models.CharField(max_length=100, verbose_name='试验用途')),
                ('parkingLocation', models.IntegerField(choices=[(0, '试验室'), (1, '停车场')], default=0, verbose_name='停放地')),
                ('transport', models.IntegerField(choices=[(0, '不可拖运'), (1, '可拖回')], default=0, verbose_name='是否可运输')),
                ('testProgress', models.IntegerField(choices=[(0, '进行中'), (1, '已拖回')], default=0, verbose_name='试验进度')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '车辆管理',
                'verbose_name_plural': '车辆管理',
                'db_table': 'vmms',
            },
        ),
    ]
