# Generated by Django 2.0.5 on 2018-09-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lmms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(max_length=255, verbose_name='车型')),
                ('useTest', models.IntegerField(choices=[(0, '请选择试验用途'), (1, '排放油耗试验'), (2, '温度场试验'), (3, '冷却试验'), (4, '空调试验')], default=0, verbose_name='试验用途')),
                ('testProgress', models.IntegerField(choices=[(0, '进行中'), (1, '试验完成')], default=0, verbose_name='试验进度')),
                ('VIN', models.CharField(max_length=17, verbose_name='VIN码')),
                ('engineNumber', models.CharField(max_length=17, verbose_name='发动机号')),
                ('mileage', models.IntegerField(verbose_name='里程(KM)')),
                ('recipient', models.CharField(max_length=5, verbose_name='接车人')),
                ('sampleDate', models.DateTimeField(verbose_name='接车时间')),
                ('returnDate', models.DateTimeField(verbose_name='还车时间')),
                ('transport', models.IntegerField(choices=[(0, '不可拖运'), (1, '可拖回')], default=0, verbose_name='是否可运输')),
                ('parkingLocation', models.IntegerField(choices=[(0, '试验室'), (1, '停车场')], default=0, verbose_name='停放地')),
                ('remarks', models.TextField(verbose_name='备注')),
            ],
        ),
    ]
