# Generated by Django 2.0.5 on 2018-09-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lmms',
            new_name='Vmms',
        ),
    ]
