# Generated by Django 2.0.5 on 2018-09-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180917_1700'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vmms',
            table='vmms',
        ),
    ]
