# Generated by Django 2.1.1 on 2018-09-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180917_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vmms',
            options={'verbose_name': '车辆管理', 'verbose_name_plural': '车辆管理'},
        ),
        migrations.AlterField(
            model_name='vmms',
            name='testProgress',
            field=models.IntegerField(choices=[(0, '进行中'), (1, '完成')], default=0, verbose_name='试验进度'),
        ),
    ]
