# Generated by Django 2.1.1 on 2018-09-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180928_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='overTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overDate', models.DateField(verbose_name='加班日期')),
                ('startTime', models.TimeField(verbose_name='开始时间')),
                ('endTime', models.TimeField(verbose_name='结束时间')),
                ('overTimeCause', models.CharField(max_length=255, verbose_name='加班事由')),
            ],
        ),
    ]
