# Generated by Django 2.1.1 on 2018-09-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_overtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtime',
            options={'verbose_name': '加班统计', 'verbose_name_plural': '加班统计'},
        ),
        migrations.AlterModelTable(
            name='overtime',
            table='overtime',
        ),
    ]
