# Generated by Django 2.1.1 on 2018-10-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180929_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmms',
            name='engineDisplacement',
            field=models.CharField(blank=True, max_length=10, verbose_name='发动机排量'),
        ),
        migrations.AddField(
            model_name='vmms',
            name='gearBox',
            field=models.CharField(blank=True, max_length=100, verbose_name='变速箱'),
        ),
        migrations.AlterField(
            model_name='vmms',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='vmms',
            name='returnDate',
            field=models.DateTimeField(blank=True, verbose_name='还车时间'),
        ),
    ]
