# Generated by Django 2.1.1 on 2018-11-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20181008_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmms',
            name='returnDate',
            field=models.DateField(blank=True, verbose_name='还车时间'),
        ),
        migrations.AlterField(
            model_name='vmms',
            name='sampleDate',
            field=models.DateField(verbose_name='接车时间'),
        ),
        migrations.AlterField(
            model_name='vmms',
            name='testProgress',
            field=models.IntegerField(choices=[(0, '进行中'), (1, '已拖回')], default=0, verbose_name='试验进度'),
        ),
        migrations.AlterField(
            model_name='vmms',
            name='useTest',
            field=models.IntegerField(choices=[(0, '请选择试验用途'), (1, '排放油耗试验'), (2, '温度场试验'), (3, '冷却试验'), (4, '空调试验'), (5, '其他')], default=0, verbose_name='试验用途'),
        ),
    ]
