# Generated by Django 2.1.1 on 2018-11-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20181130_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmms',
            name='useTest',
            field=models.CharField(max_length=100, verbose_name='试验用途'),
        ),
    ]
